language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'stable'
  - 'lts/*'
after_success:
  - npm run semantic-release
install:
  - npm install
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
