language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'stable'
  - 'lts/*'
before_script:
  - npm prune --production
after_success:
  - npm run semantic-release
branches:
  only:
    - master
