language: node_js

node_js:
  - 'stable'
  - 'lts/*'

cache:
  directories:
    - node_modules

after_success:
  - npm install semantic-release

deploy:
  skip_cleanup: true
  provider: script
  script: semantic-release pre && npm publish && semantic-release post || true
  on:
    branch: master

branches:
  only:
  - master
